apiVersion: v1
kind: Service
metadata:
  name: meow
  labels:
    app: cats
    component: assign2cat
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: cats
    component: assign2cat