apiVersion: v1
kind: Service
metadata:
  name: bark
  labels:
    app: dogs
    component: assign2dog
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 80
    nodePort: 30001
  selector:
    app: dogs
    component: assign2dog